language: cpp

compiler:
- gcc
- clang

addons:
apt:
 sources:
  - ubuntu-toolchain-r-test
  - llvm-toolchain-precise-3.7
 packages:
  - cmake
  - cmake-data
  - clang-3.7
  - g++-7

script:
- cd hello_world_application
- cmake -H. -B_build
- cmake --build _build
- cmake --build _build --target hello_world
- ./_build/hello_world
- echo "Hello world application testing is done"
- cd ..
- cd solver_application
- cmake -H. -B_build
- cmake --build _build
- cmake --build _build --target solver
- echo "Solver application testing is done"
